name: Check Melon Tickets

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Monitor Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 211159      # 替换为实际演出ID
          schedule-id: 20250523     # 替换为场次ID
          seat-id: 1_0           # 座位区域ID
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}  # Slack通知地址
          message: '有票了！！'
